name: 'WeiDU Mod Package Builder (iemod, lin, osx: amd64; win: x86; use tp2 VERSION suffix)'

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  call_workflow_amd64:
    strategy:
      matrix:
        type: [iemod, linux, macos]

    permissions:
      contents: write

    uses: argent77test/TestActionGlobal/.github/workflows/TestActionGlobal.yml@master
    with:
      type: ${{ matrix.type }}
      architecture: amd64
      suffix: version

  call_workflow_x86:
    permissions:
      contents: write

    uses: argent77test/TestActionGlobal/.github/workflows/TestActionGlobal.yml@master
    with:
      type: windows
      architecture: x86
      suffix: version
