name: 'WeiDU Mod Package Builder (iemod; win/lin/mac: amd64; use tp2 VERSION suffix)'

on:
  # release:
    # types: [published]
  workflow_dispatch:

jobs:
  call_workflow:
    strategy:
      matrix:
        # type: [iemod, windows, linux, macos]
        type: [iemod]

    permissions:
      contents: write

    uses: argent77test/TestActionGlobal/.github/workflows/TestActionGlobal.yml@master
    with:
      type: ${{ matrix.type }}
      architecture: amd64
      suffix: 'v0.9 (beta)'
