name: 'WeiDU Mod Package Builder (iemod; multi: amd64; use tp2 VERSION suffix)'

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  call_workflow:
    strategy:
      matrix:
        type: [iemod, multi]

    permissions:
      contents: write

    uses: argent77test/TestActionGlobal/.github/workflows/TestActionGlobal.yml@master
    with:
      type: ${{ matrix.type }}
      architecture: amd64
      suffix: ${{ github.event.release.tag_name }}
      naming: ini
      weidu_version: latest
      multi_autoupdate: false
