name: 'WeiDU Mod Package Builder (test)'

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  call_workflow:
    permissions:
      contents: write

    uses: argent77test/TestActionGlobal/.github/workflows/TestActionGlobal.yml@master
    with:
      type: iemod
      architecture: amd64
      suffix: 'v0.9 (beta)'
